### This script contains the following sections:

#### 1. Importing libraries
#### 2. Import and Convert Dataset for Variable Selection
#### 3. Import and Combine Converted Datasets

# 1. Library Imports

In [62]:
import pandas as pd
import numpy as np
import os
import glob

In [63]:
path = r'C:\Users\Achievement 6\data_emergency_ex6.1\Data'
col_path = r'C:\Users\Achievement 6\EX6.1'

# 2. Imported Converted Datasets for Variable Selection

In [64]:
files = glob.glob(path + '\Original\[2].Converted\*.csv')
# files

In [65]:
#import multiple csv file

df_list = {}

for file in files:
  
    file_name = file.split('\\')[11]
    
    file_df = pd.read_csv(os.path.join(path,'Original','2.Converted', file_name), index_col = 0)

    file_name = 'df_' + file_name.split('-')[0]
    
    df_list[file_name] = file_df.reset_index()
    
#     print(files)

In [66]:
print(df_list.keys())

dict_keys(['df_2005', 'df_2006', 'df_2007', 'df_2008', 'df_2009', 'df_2010', 'df_2011', 'df_2012', 'df_2013', 'df_2014', 'df_2015', 'df_2016', 'df_2017', 'df_2018', 'df_2019', 'df_2020'])

In [67]:
# insert year column for datasets without 
col = 'datayear'

for df_name, df in df_list.items():
    if col not in df.columns:
        df[col] = np.nan
        df_name = df_name.strip()[3:] + '-hospital-emergency-department-characteristics-by-facility-pivot-profile.csv'
        df.to_csv(os.path.join(path,'Original','2.Converted', df_name))
        print(df_name, df.columns[-1])

In [68]:
#change column names for all datasets before concat
#Since the column names vary, I chose to ue the list of column names from the 2020 dataset. 

#load chosen columns for each dataset. The columns were chosen manually due to inconsistencies in the 
# column names and their order in the individual datasets

cols_names_ordered = pd.read_csv(os.path.join(col_path,'column_names.csv'), header = None)

cols_names_ordered = cols_names_ordered.iloc[:,1:]
# cols_names.isna().sum()
cols_names_ordered

,1,2,3,4,5,6,7,8,9,10,...,44,45,46,47,48,49,50,51,52,53
0,datayear,oshpd_id9,COUNTY,FAC_ADDRESS_ONE,FAC_CITY,FAC_ZIPCODE,TYPE_LIC,TYPE_CNTRL,TRAUMA_CTR,ED_LIC_LEVL_BEGIN,...,SN_IC_Care,Medi_Cal,Medicare,Other_Payer,Private_Coverage,SelfPay,ED_Visit,All_Other,English,Spanish
1,datayear,oshpd_id9,COUNTY,FAC_ADDRESS_ONE,FAC_CITY,FAC_ZIPCODE,TYPE_LIC,TYPE_CNTRL,TRAUMA_CTR,ED_LIC_LEVL_BEGIN,...,SN_IC_Care,Medi_Cal,Medicare,Other_Payer,Private_Coverage,SelfPay,ED_Visit,All_Other,English,Spanish
2,datayear,oshpd_id9,COUNTY,FAC_ADDRESS_ONE,FAC_CITY,FAC_ZIPCODE,TYPE_LIC,TYPE_CNTRL,TRAUMA_CTR,ED_LIC_LEVL_BEGIN,...,SN_IC_Care,Medi_Cal,Medicare,Other_Payer,Private_Coverage,SelfPay,ED_Visit,All_Other,English,Spanish
3,datayear,oshpd_id9,COUNTY,FAC_ADDRESS_ONE,FAC_CITY,FAC_ZIPCODE,TYPE_LIC,TYPE_CNTRL,TRAUMA_CTR,ED_LIC_LEVL_BEGIN,...,SN_IC_Care,Medi_Cal,Medicare,Other_Payer,Private_Coverage,SelfPay,ED_Visit,All_Other,English,Spanish
4,datayear,oshpd_id9,COUNTY,FAC_ADDRESS_ONE,FAC_CITY,FAC_ZIPCODE,TYPE_LIC,TYPE_CNTRL,TRAUMA_CTR,ED_LIC_LEVL_BEGIN,...,SN_IC_Care,Medi_Cal,Medicare,Other_Payer,Private_Coverage,SelfPay,ED_Visit,All_Other,English,Spanish
5,datayear,oshpd_id9,COUNTY,FAC_ADDRESS_ONE,FAC_CITY,FAC_ZIPCODE,TYPE_LIC,TYPE_CNTRL,TRAUMA_CTR,ED_LIC_LEVL_BEGIN,...,SN_IC_Care,Medi_Cal,Medicare,Other_Payer,Private_Coverage,SelfPay,ED_Visit,All_Other,English,Spanish
6,datayear,oshpd_id9,COUNTY,FAC_ADDRESS_ONE,FAC_CITY,FAC_ZIPCODE,TYPE_LIC,TYPE_CNTRL,TRAUMA_CTR,ED_LIC_LEVL_BEGIN,...,SN_IC_Care,Medi_Cal,Medicare,Other_Payer,Private_Coverage,SelfPay,ED_Visit,All_Other,English,Spanish
7,datayear,oshpd_id2,COUNTY_NAME,DBA_ADDRESS1,DBA_CITY,DBA_ZIP_CODE,LICENSE_CATEGORY_DESC,CONTROL_TYPE_DESC,TRAUMA_CENTER_DESC,ER_SERVICE_LEVEL_DESC,...,SN_IC_Care,Medi_Cal,Medicare,Other_Payer,Private_Coverage,SelfPay,ED_Visit,All_Other,English,Spanish
8,datayear,oshpd_id2,COUNTY_NAME,DBA_ADDRESS1,DBA_CITY,DBA_ZIP_CODE,LICENSE_CATEGORY_DESC,Cntrl_Type_Desc,TRAUMA_CENTER_DESC,ER_SERVICE_LEVEL_DESC,...,SN_IC_Care,Medi_Cal,Medicare,Other_Payer,Private_Coverage,SelfPay,ED_Visit,All_Other,English,Spanish
9,datayear,oshpd_id2,COUNTY_NAME,DBA_ADDRESS1,DBA_CITY,DBA_ZIP_CODE,LICENSE_CATEGORY_DESC,Control_Type_Desc,TRAUMA_CENTER_DESC,ER_SERVICE_LEVEL_DESC,...,SN_IC_Care,Medi_Cal,Medicare,Other_Payer,Private_Coverage,SelfPay,ED_Visit,All_Other,English,Spanish
10,datayear,oshpd_id2,COUNTY_NAME,DBA_ADDRESS1,DBA_CITY,DBA_ZIP_CODE,LICENSE_CATEGORY_DESC,Control_Type_Desc,TRAUMA_CENTER_DESC,ER_SERVICE_LEVEL_DESC,...,SN_IC_Care,Medi_Cal,Medicare,Other_Payer,Private_Coverage,SelfPay,ED_Visit,All_Other,English,Spanish
11,datayear,oshpd_id2,county_name,DBA_ADDRESS1,DBA_CITY,DBA_ZIP_CODE,license_type_desc,control_type_desc,TRAUMA_CENTER_DESC,ed_lic_levl_end,...,SN_IC_Care,Medi_Cal,Medicare,Other_Payer,Private_Coverage,SelfPay,ED_Visit,All_Other_Languages,English,Spanish
12,datayear,oshpd_id2,county_name,DBA_ADDRESS1,DBA_CITY,DBA_ZIP_CODE,LICENSE_CATEGORY_DESC,control_type_desc,TRAUMA_CENTER_DESC,ed_lic_levl_end,...,SN_IC_Care,Medi_Cal,Medicare,Other_Payer,Private_Coverage,SelfPay,ED_Visit,All_Other_Languages,English,Spanish
13,datayear,oshpd_id2,county_name,DBA_ADDRESS1,DBA_CITY,DBA_ZIP_CODE,LICENSE_CATEGORY_DESC,control_type_desc,TRAUMA_CENTER_DESC,ed_lic_levl_end,...,SN_IC_Care,Medi_Cal,Medicare,Other_Payer,Private_Coverage,SelfPay,ED_Visit,All_Other_Languages,English,Spanish
14,datayear,oshpd_id2,COUNTY_NAME,DBA_ADDRESS1,DBA_CITY,DBA_ZIP_CODE,LICENSE_CATEGORY_DESC,CONTROL_TYPE_DESC,TRAUMA_CENTER_DESC,ER_SERVICE_LEVEL_DESC,...,disp_SN_IC_Care,Medi_Cal,Medicare,Other_Payer,Private_Coverage,SelfPay,ED_Visit,All_Other_Languages,English,Spanish
15,datayear,oshpd_id2,COUNTY_NAME,DBA_ADDRESS1,DBA_CITY,DBA_ZIP_CODE,LICENSE_CATEGORY_DESC,CONTROL_TYPE_DESC,TRAUMA_CENTER_DESC,ER_SERVICE_LEVEL_DESC,...,disp_SN_IC_Care,Medi_Cal,Medicare,Other_Payer,Private_Coverage,SelfPay,ED_Visit,All_Other_Languages,English,Spanish

In [69]:
# x = ['fac_id','COUNTY']
# x = cols_names_ordered.iloc[0,:].tolist()
# x = cols_names_ordered[['fac_id','COUNTY']]
# df_list['df_2010'].columns.str.replace(' ','')

In [70]:
# cols_names_ordered.iloc[,0]
# df_list['df_2012']

In [71]:
df_list['df_2013']

,index,datayear,oshpd_id2,COUNTY_NAME,DBA_ADDRESS1,DBA_CITY,DBA_ZIP_CODE,LICENSE_CATEGORY_DESC,Cntrl_Type_Desc,TRAUMA_CENTER_DESC,...,SN_IC_Care,Medi_Cal,Medicare,Other_Payer,Private_Coverage,SelfPay,ED_Visit,All_Other,English,Spanish
0,0,2013,106010735,ALAMEDA,2070 CLINTON AVE,ALAMEDA,94501,General Acute Care Hospital,Public - District,NaN,...,220.0,373,2788,3493.0,4306.0,NaN,13538,600.0,12671,267
1,1,2013,106010739,ALAMEDA,2450 ASHBY AVENUE,BERKELEY,94705,General Acute Care Hospital,Non-Profit - Corporation,NaN,...,187.0,9160,7719,1623.0,12251.0,NaN,36972,808.0,34964,1200
2,2,2013,106010776,ALAMEDA,747 52ND STREET,OAKLAND,94609,General Acute Care Hospital,Non-Profit - Corporation,Level I - Pediatric,...,1.0,28805,27,527.0,5689.0,NaN,38211,1345.0,26729,10137
3,3,2013,106010846,ALAMEDA,1411 EAST 31ST STREET,OAKLAND,94602,General Acute Care Hospital,Public - City or County,Level II,...,243.0,17115,5141,39539.0,1621.0,NaN,72496,4420.0,55464,12612
4,4,2013,106010856,ALAMEDA,280 W. MACARTHUR BOULEVARD,OAKLAND,94611,General Acute Care Hospital,Non-Profit - Corporation,NaN,...,249.0,14639,17381,2128.0,41768.0,NaN,85460,1671.0,78438,5351
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,320,2013,106560525,VENTURA,2975 NORTH SYCAMORE DRIVE,SIMI VALLEY,93065,General Acute Care Hospital,Non-Profit - Corporation,NaN,...,52.0,7064,3318,571.0,10447.0,NaN,25494,114.0,24263,1117
321,321,2013,106560529,VENTURA,1600 NORTH ROSE AVENUE,OXNARD,93030,General Acute Care Hospital,Non-Profit - Corporation,NaN,...,45.0,16048,8048,3761.0,8288.0,NaN,46235,87.0,37898,8250
322,322,2013,106571086,YOLO,1325 COTTONWOOD STREET,WOODLAND,95695,General Acute Care Hospital,Non-Profit - Corporation,NaN,...,188.0,6899,3957,1700.0,4171.0,NaN,18972,258.0,16237,2477
323,323,2013,106574010,YOLO,2000 SUTTER PLACE,DAVIS,95616,General Acute Care Hospital,Non-Profit - Corporation,NaN,...,126.0,6283,4371,777.0,8161.0,NaN,22162,556.0,19163,2443
324,324,2013,106580996,YUBA,726 FOURTH ST,MARYSVILLE,95901,General Acute Care Hospital,Non-Profit - Corporation,Level III,...,NaN,20532,7274,2279.0,6705.0,NaN,45093,1496.0,40149,3448

In [72]:
# rename all datasets before column selection
#make a new df list with df with chosen columns

df_list_updated = {}
i = 0 #declared I inside and it was not looping. wow! took a while
for df_name, df in df_list.items():
    df_filtered = df.copy()
    df_filtered = df_filtered[cols_names_ordered.iloc[i]]
    df_list_updated[df_name] = df_filtered
    print(df_name, df_filtered.shape, 'index for df is {}'.format(i))
    i = i + 1

df_2005 (346, 53) i is 0
df_2006 (343, 53) i is 1
df_2007 (344, 53) i is 2
df_2008 (335, 53) i is 3
df_2009 (332, 53) i is 4
df_2010 (327, 53) i is 5
df_2011 (328, 53) i is 6
df_2012 (332, 53) i is 7
df_2013 (325, 53) i is 8
df_2014 (333, 53) i is 9
df_2015 (328, 53) i is 10
df_2016 (326, 53) i is 11
df_2017 (331, 53) i is 12
df_2018 (334, 53) i is 13
df_2019 (326, 53) i is 14
df_2020 (320, 53) i is 15

In [73]:
# df_list_updated['df_2005'].iloc[:,0]
df_list_updated['df_2005'].columns[0]

'datayear'

In [74]:
#Selected chosen columns excluding the first one (2020 column names). This will be applied to all datasets

col_names_selected = cols_names_ordered.iloc[10,].tolist()
print(col_names_selected)

['datayear', 'oshpd_id2', 'COUNTY_NAME', 'DBA_ADDRESS1', 'DBA_CITY', 'DBA_ZIP_CODE', 'LICENSE_CATEGORY_DESC', 'Control_Type_Desc', 'TRAUMA_CENTER_DESC', 'ER_SERVICE_LEVEL_DESC', 'RURAL_HOSPITAL_DESC', 'TEACHING_HOSPITAL_DESC', 'LICENSED_BED_SIZE', 'MSSA_DESIGNATION', 'Sex_Male', 'Sex_Female', 'Sex_Unk', 'Age_01_09', 'Age_10_19', 'Age_20_29', 'Age_30_39', 'Age_40_49', 'Age_50_59', 'Age_60_69', 'Age_70_79', 'Age_80_', 'Age_Under_1', 'Age_Unknown', 'Asian_Pacific_Island', 'Black', 'Hispanic', 'Native_American_Eski', 'Other_Race', 'Unknown_Race', 'White', 'Acute_Care', 'Against_Medical_Advice', 'Died', 'Hospice_Care', 'Home_Health_Service', 'Residential_Care', 'Routine', 'Psychiatric_Care', 'SN_IC_Care', 'Medi_Cal', 'Medicare', 'Other_Payer', 'Private_Coverage', 'SelfPay', 'ED_Visit', 'All_Other', 'English', 'Spanish']

In [87]:
# give the columns a unified names across all datasets

for df_name, df in df_list_updated.items():
    
    for i,col in enumerate(df.columns):
        df.rename(columns={col: col_names_selected[i]}, inplace = True)
#         print(i, col_names_selected[i])

    df['datayear'] = df_name.strip()[3:] # fill missing year values before merging dataset
    
    df_name = 'cols_standardized' + df_name.strip()[3:] + '-hospital-emergency-department-characteristics-by-facility-pivot-profile.csv'
    
    df.to_csv(os.path.join(path,'Original','3.Updated', df_name), index = 0)
    
    print(df_name, 'was saved successfully')
    
#     df_name = 'cols_standardized' + df_name.strip()[3:] + '-hospital-emergency-department-characteristics-by-facility-pivot-profile.csv'
#     df.to_csv(os.path.join(path,'Original','Converted', df_name))

cols_standardized2005-hospital-emergency-department-characteristics-by-facility-pivot-profile.csv was saved successfully
cols_standardized2006-hospital-emergency-department-characteristics-by-facility-pivot-profile.csv was saved successfully
cols_standardized2007-hospital-emergency-department-characteristics-by-facility-pivot-profile.csv was saved successfully
cols_standardized2008-hospital-emergency-department-characteristics-by-facility-pivot-profile.csv was saved successfully
cols_standardized2009-hospital-emergency-department-characteristics-by-facility-pivot-profile.csv was saved successfully
cols_standardized2010-hospital-emergency-department-characteristics-by-facility-pivot-profile.csv was saved successfully
cols_standardized2011-hospital-emergency-department-characteristics-by-facility-pivot-profile.csv was saved successfully
cols_standardized2012-hospital-emergency-department-characteristics-by-facility-pivot-profile.csv was saved successfully
cols_standardized2013-hospital-emergency-department-characteristics-by-facility-pivot-profile.csv was saved successfully
cols_standardized2014-hospital-emergency-department-characteristics-by-facility-pivot-profile.csv was saved successfully
cols_standardized2015-hospital-emergency-department-characteristics-by-facility-pivot-profile.csv was saved successfully
cols_standardized2016-hospital-emergency-department-characteristics-by-facility-pivot-profile.csv was saved successfully
cols_standardized2017-hospital-emergency-department-characteristics-by-facility-pivot-profile.csv was saved successfully
cols_standardized2018-hospital-emergency-department-characteristics-by-facility-pivot-profile.csv was saved successfully
cols_standardized2019-hospital-emergency-department-characteristics-by-facility-pivot-profile.csv was saved successfully
cols_standardized2020-hospital-emergency-department-characteristics-by-facility-pivot-profile.csv was saved successfully

# 3. Load and Combine Converted Datasets

In [88]:
files = glob.glob(path + '/Original/[3].Updated/*.csv')

prepared_df = {}

for file in files:
  
    file_name = file.split('\\')[10]
    
    file_df = pd.read_csv(os.path.join(path,'Original','3.Updated', file_name), index_col = 0)

    file_name = file_name.split('-')[0]
    
    prepared_df[file_name] = file_df.reset_index()

In [89]:
prepared_df.keys()

dict_keys(['cols_standardized2005', 'cols_standardized2006', 'cols_standardized2007', 'cols_standardized2008', 'cols_standardized2009', 'cols_standardized2010', 'cols_standardized2011', 'cols_standardized2012', 'cols_standardized2013', 'cols_standardized2014', 'cols_standardized2015', 'cols_standardized2016', 'cols_standardized2017', 'cols_standardized2018', 'cols_standardized2019', 'cols_standardized2020'])

In [ ]:
# prepared_df.values()

In [90]:
df_to_merge = prepared_df.values()
df_combined = pd.concat(df_to_merge).drop_duplicates().reset_index(drop = True)
df_combined.shape

(5310, 53)

In [91]:
df_combined.tail()

,datayear,oshpd_id2,COUNTY_NAME,DBA_ADDRESS1,DBA_CITY,DBA_ZIP_CODE,LICENSE_CATEGORY_DESC,Control_Type_Desc,TRAUMA_CENTER_DESC,ER_SERVICE_LEVEL_DESC,...,SN_IC_Care,Medi_Cal,Medicare,Other_Payer,Private_Coverage,SelfPay,ED_Visit,All_Other,English,Spanish
5305,2020,106560525,Ventura,2975 Sycamore Dr,Simi Valley,93065,General Acute Care Hospital,Non-profit Corporation (incl. Church-related),NaN,Emergency - Basic,...,61.0,8941.0,5341.0,641.0,8516.0,1584.0,25051.0,116.0,23065.0,1866.0
5306,2020,106560529,Ventura,1600 N Rose Ave,Oxnard,93030,General Acute Care Hospital,Non-profit Corporation (incl. Church-related),NaN,Emergency - Basic,...,60.0,18418.0,6674.0,1863.0,5037.0,3299.0,35291.0,143.0,26822.0,8255.0
5307,2020,106571086,Yolo,1325 Cottonwood St,Woodland,95695,General Acute Care Hospital,Non-profit Corporation (incl. Church-related),NaN,Emergency - Basic,...,57.0,8618.0,4075.0,447.0,4387.0,1397.0,18924.0,399.0,15962.0,2537.0
5308,2020,106574010,Yolo,2000 Sutter Pl,Davis,95616,General Acute Care Hospital,Non-profit Corporation (incl. Church-related),NaN,Emergency - Basic,...,142.0,7814.0,4540.0,665.0,6935.0,1177.0,21131.0,609.0,18037.0,2443.0
5309,2020,106580996,Yuba,726 Fourth St,Marysville,95901,General Acute Care Hospital,Investor - Limited Liability Company,Level III,Emergency - Basic,...,107.0,27267.0,9844.0,2278.0,7931.0,5140.0,52468.0,1251.0,48607.0,2555.0

In [92]:
df_combined.to_csv(os.path.join(path,'Prepared', 'df_combined.csv'), index = 0)

In [93]:
df_combined.isnull().sum()

datayear                     0
oshpd_id2                    0
COUNTY_NAME                  0
DBA_ADDRESS1                 0
DBA_CITY                     0
DBA_ZIP_CODE                 0
LICENSE_CATEGORY_DESC        3
Control_Type_Desc            1
TRAUMA_CENTER_DESC        4400
ER_SERVICE_LEVEL_DESC       71
RURAL_HOSPITAL_DESC       4302
TEACHING_HOSPITAL_DESC    2086
LICENSED_BED_SIZE            1
MSSA_DESIGNATION          2687
Sex_Male                   107
Sex_Female                 107
Sex_Unk                   3218
Age_01_09                  115
Age_10_19                  107
Age_20_29                  119
Age_30_39                  126
Age_40_49                  130
Age_50_59                  128
Age_60_69                  131
Age_70_79                  138
Age_80_                    149
Age_Under_1                128
Age_Unknown               4558
Asian_Pacific_Island       152
Black                      146
Hispanic                   114
Native_American_Eski       277
Other_Race                 206
Unknown_Race               335
White                      366
Acute_Care                 159
Against_Medical_Advice     303
Died                       213
Hospice_Care              1895
Home_Health_Service       1424
Residential_Care          2118
Routine                    108
Psychiatric_Care           783
SN_IC_Care                 453
Medi_Cal                   123
Medicare                   126
Other_Payer                127
Private_Coverage           128
SelfPay                   3081
ED_Visit                   107
All_Other                 1470
English                   1445
Spanish                   1450
dtype: int64